name: fielder_models
description: A new Flutter module for fielder models

version: 0.0.4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^1.0.1
  google_maps_flutter: ^2.0.1
  intl:
  json_schema: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.fielder.fielder_models
    iosBundleIdentifier: com.fielder.fielderModels
