name: fielder_models
description: A new Flutter module for fielder models

version: 0.0.6-no-outed-packages

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.4.0
  google_maps_flutter: ^2.0.0
  intl:
  tuple: ^2.0.0 

flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.fielder.fielder_models
    iosBundleIdentifier: com.fielder.fielderModels
