enum FirebaseAuthStatusEnum {
  // Status
  VERIFICATION_LINK_SENT,
  RESET_LINK_SENT,

  // Exception
  ERROR_WEAK_PASSWORD,
  ERROR_INVALID_EMAIL,
  ERROR_EMAIL_ALREADY_IN_USE,
  USER_NOT_FOUND,
  ERROR_UNDEFINED,
}
